version: "3"
services:
 postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: db
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file: 
      - ./client/.env
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file: 
      - ./server/.env
    ports:
      - "5000:5000"
    restart: always